# Numpy

Hoje, vamos começara ver a biblioteca matemática mais importante pro ecossistema 
científico do Python: O Numpy.

Vamos relembrar alguns conceitos

In [1]:
lista = ["a", 2, 2.4, True, [1, 3], {"a": 1}]

In [2]:
lista.append("Olá")

In [3]:
lista

['a', 2, 2.4, True, [1, 3], {'a': 1}, 'Olá']

In [4]:
a = 42.5

In [5]:
a = 'aaaaa'

In [6]:
a

'aaaaa'

A biblioteca **NumPy** _(Numerical Python)_ proporciona uma forma eficiente de armazenagem e processamento de conjuntos de dados, e é utilizada como base para a construção da biblioteca Pandas, que estudaremos a seguir.

O diferencial do Numpy é sua velocidade e eficiência, o que faz com que ela seja amplamente utilizada para computação científica e analise de dados. 

A velocidade e eficiência é possível graças à estrutura chamada **numpy array**, que é um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

In [56]:
# A gente importa o numpy sempre chamando ele de "np"
import numpy as np

In [8]:
# Vamos fazer uma comparação com uma lista de Python
py_array = [[1,   2,  3]]

print(py_array)
print(type(py_array))

[[1, 2, 3]]
<class 'list'>


In [9]:
# Uma lista com 2 dimensões é uma lista de listas
print(type(py_array[0]))

<class 'list'>


In [10]:
# Nota como o tipo da variável muda para "ndarray"
np_array = np.array(py_array)

print(np_array)
print(type(np_array))

[[1 2 3]]
<class 'numpy.ndarray'>


In [11]:
py_array_string = [['a',   2,  3]]
np_array_string = np.array(py_array_string)

print(np_array_string)
print(type(np_array_string))
print(np_array_string.dtype) 

[['a' '2' '3']]
<class 'numpy.ndarray'>
<U11


In [12]:
# Mas no  numpy, um ndarray continua sendo formado de ndarrays.
print(type(np_array[0]))

<class 'numpy.ndarray'>


In [13]:
# 3 atributos básicos pra um ndarray
print(np_array.shape)   # O formato dele
print(np_array.ndim)    # Quantas dimensões ele tem
print(np_array.dtype)   # O "dtype", que é o tipo dos elementos (número, letra, ...) dele

(1, 3)
2
int32


In [14]:
x = np.array([1, 2, 3]) # Um vetor também é um ndarray
print(type(x))
print(x.dtype)

<class 'numpy.ndarray'>
int32


In [15]:
# O dtype de um array do numpy pode ser controlado na hora que a gente cria.
py_array = [1,   2,  3]

array_int = np.array(py_array, dtype=np.float64)

In [16]:
print(array_int)
print(array_int.dtype)

[1. 2. 3.]
float64


In [17]:
# Mas quando a gente não define, ele infere a partir dos nossos dados.
py_array_2 = [1.0,   2,  3.0]

array_float = np.array(py_array_2)

print(array_float)
print(array_float.dtype)

[1. 2. 3.]
float64


In [18]:
# Para selecionar um elemento de uma tabela no Python e no Numpy, tem uma ligeira diferença.
print((array_float[2])) # Python: Pega a primeira linha. Dela, pega o primeiro elemento.

3.0


**Revisando**

In [19]:
# No Python, existe o conceito de "indexing", que é pegar elementos pelo seu índice (a sua posição) 
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(lista[0])
print(lista[3])
print(lista[-1]) # Aqui a gente também pode indexar negativamente. Aí o Python conta de trás pra frente.
print(lista[-3]) # -3 vai ser o terceiro elemento, de trás pra frente

# OBS: Lembre-se que as "posições" no Python sempre começam a contar do zero!!!

1
4
9
7


In [20]:
print(lista[0] == lista[-9]) # Nota que o primeiro elemento é o -9, pois é o nono de trás pra frente.

True


In [21]:
# Também existe uma forma de pegar um subconjunto da lista.
# A gente chama isso de "slicing". Nota que o último elemento não entra!
print(lista[:])
print(lista[2:3])
print(lista[:-3]) # A gente pode usar nossa indexação negativa aqui.

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[3]
[1, 2, 3, 4, 5, 6]


In [22]:
# Podemos definir um início também pro slicing.
# Quando não colocamos nada, ele assume que o início é 0.
# No caso do fim, se não colocamos nada, ele assume que o fim é o último elemento.
print(lista[2:])
print(lista[2:3])
print(lista[2:-3]) # A gente pode usar nossa indexação negativa aqui.

[3, 4, 5, 6, 7, 8, 9]
[3]
[3, 4, 5, 6]


In [23]:
# O poder do slicing é que a gente pode definir diferentes tamanhos de passo.
print(lista[0:9:2])
print(lista[::-1]) # Agora ele anda de trás pra frente!
print(lista[1:5:-1]) # Se eu for subtraindo 1, é impossível ir de 1 até 5. Logo, gera uma lista vazia.

[1, 3, 5, 7, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[]


Também podemos aplicar o conceito do slicing no numpy

In [24]:
print(array_int)
print(array_int[2]) # Pegando o terceiro elemento
print(array_int[:1])
print(array_int[-1:-5:-2]) # Invertendo o array

[1. 2. 3.]
3.0
[1.]
[3. 1.]


**Funções numpy**  
O numpy também tem diversas funções para facilitar criação de arrays.

In [25]:
print(np.zeros(10), end='\n\n') # O "end" muda o que o Python encaixa no fim do que ele mostra pra gente.
print(np.ones(5), end='\n\n') # \n é pular linha, e é o default. \n\n pula 2 linhas.
# Alguns spoilers
print(np.identity(4), end='\n\n')
print(np.eye(4, 3), end='\n\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1.]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]



In [26]:
# Relembrando a função range
list(range(2, 10, 2))

[2, 4, 6, 8]

In [27]:
# Também podemos fazer listas de números.
print(np.arange(10, 30, 2)) # Lista de números inteiros pulando de 2 em 2. Mas até aqui, seria igual a Python.
print('')
print(np.arange(10.5, 30.5, 2))  # Lista de números de ponto flutuant, pulando de 2 em 2.
print('')
print(np.linspace(10, 30, 10)) # Lista de 10 números, igualmente espaçados entre 10 e 30.

[10 12 14 16 18 20 22 24 26 28]

[10.5 12.5 14.5 16.5 18.5 20.5 22.5 24.5 26.5 28.5]

[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]


# Operações Básicas

In [28]:
# Se a força do numpy é ter tudo operando como vetores, 
# então ele tem que ter operações de vetores.
vec1 = np.arange(0, 10, 1)
vec2 = np.arange(0, 20, 2)

print(vec1)
print(vec2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [29]:
# Soma por elemento
print(vec1 + vec2)

[ 0  3  6  9 12 15 18 21 24 27]


In [30]:
# Multiplicação elemento por elemento
print(vec1 * vec2)

[  0   2   8  18  32  50  72  98 128 162]


In [31]:
# produto de matrizes (neste caso, produto escalar)
# Isso é multiplicar elemento por elemento, e depois somar
print(vec1 @ vec2)
print((vec1 * vec2).sum()) # Todo ndarray tem um método "sum" pra somar seus elementos

# produto de matrizes (neste caso, produto escalar)
# Outra forma de escrever a mesma coisa
print(vec1.dot(vec2))

570
570
570


## Bora praticar!

Fonte: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb


1) Inverta um vetor (o primeiro elemento vira o último). Para testar crie um vetor a partir da seguinte lista [0, 5, 1, 9, 9, 87]

In [32]:
lista = [0, 5, 1, 9, 9, 87]
vetor = np.array(lista)
print(vetor[::-1])

[87  9  9  1  5  0]


2) Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [33]:
print(np.arange(1, 22, 2))

[ 1  3  5  7  9 11 13 15 17 19 21]


In [34]:
array_num = np.arange(1, 21, 2)
print(array_num)

[ 1  3  5  7  9 11 13 15 17 19]


3) Ache os índices dos elementos não-zero a partir do array [1,2,0,0,4,0]

In [35]:
lista2 = [1,2,0,0,4,0]
lista_indices_nao_zero = [idx for idx in range(len(lista2)) if lista2[idx] != 0]
lista_indices_nao_zero

[0, 1, 4]

In [36]:
vetor = np.array ([1, 2, 0, 0, 4, 0])
idx = 0

for elemento in vetor:
    if elemento != 0:
        print (idx)
    idx +=1

0
1
4


In [37]:
vec1 = np.array([1,2,0,0,4,0])
np.where(vec1 != 0)

(array([0, 1, 4], dtype=int64),)

In [38]:
lista_numeros = [1,2,0,0,4,0]
array_numeros = np.array(lista_numeros)
for idx,x in enumerate(array_numeros) :
    if x != 0:
        print(f'o número {x} está no indice=>{idx}')

o número 1 está no indice=>0
o número 2 está no indice=>1
o número 4 está no indice=>4


In [39]:
np.nonzero(array_numeros)

(array([0, 1, 4], dtype=int64),)

In [40]:
vec1 = np.array([1,2,0,0,4,0,4])
np.argwhere(vec1)

array([[0],
       [1],
       [4],
       [6]], dtype=int64)

E se a gente quisesse pegar os elementos diferentes de zero?

In [41]:
lista_num = [1,2,0,0,4,0]
array_num = np.array(lista_num)
array_nozero_element = [array_num[x] for x in range(len(array_num)) if array_num[x] != 0]
array_nozero_element

[1, 2, 4]

In [42]:
a = np.array([1,2,0,0,4,0])
a_nonzero = np.array([i for i in a if i != 0])
a_nonzero

array([1, 2, 4])

In [43]:
array_num[array_num != 0]

array([1, 2, 4])

In [44]:
#Teste com listas
lista_num = [0,2,0,0,0,0]

lista_num[lista_num != 0]

2

4) Crie uma matriz identidade 3x3

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

5) Crie um array de 10 com valores aleatórios

In [46]:
np.random.rand(10)

array([0.02633752, 0.14408334, 0.43526386, 0.10033472, 0.66922589,
       0.43080696, 0.84665005, 0.34141018, 0.66295825, 0.57137816])

In [47]:
from random import randrange as rand
lista_num = [rand(1, 10) for x in range(10)]
array_num = np.array(lista_num)
array_num

array([7, 2, 1, 1, 9, 5, 4, 1, 5, 6])

In [48]:
array = np.random.randint(10, size=(10)) 
print(array)

[1 5 7 7 5 9 7 7 3 1]


6) Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [49]:
array_num = np.random.randint(100, size=(100))
print(array_num)
print(np.max(array_num))
print(np.min(array_num))

[57 99 18 55 56 40 46 15 61 94  1 67 67 41  7 47 65 68 90 80 71 14  2 70
 72 15 67 82 24 96 51 19  4 14 93 79 18 89 78  8  8 59 20 85 88 95 65 65
 25 88 80 15 32 72 76 16 34 90 53 43 51 65  4 37 65 10 93 40 38 38 74 33
 62 62 85 98 15 21 35 38 92  0 11 71 68 15 62 73 68 58 99 12 17 38 87 83
 18 61 34  0]
99
0


7) Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [50]:
a = np.ones((10,10))
b = np.zeros((8,8))
a[1:9,1:9] = b
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [51]:
ndim = 6
np_array = np.zeros((ndim, ndim))

for i in range(ndim):
    for j in range(ndim):
        if i == 0 or j == 0 or i == (ndim - 1) or j == (ndim - 1):
            np_array[i][j] = 1

np_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [52]:
array = np.zeros((2, 2))
array = np.pad(array, 1, constant_values=1)
array

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [57]:
# Agora com uma função passando os parâmetros de #linhas e #colunas
def frame_array(n_row,n_column):
    a = np.ones((n_row,n_column))
    b = np.zeros((n_row-2,n_column-2))
    a[1:n_row-1,1:n_column-1] = b
    return a
frame_array(9,8)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

8 - Como adicionar uma borda de 0's ao redor de um array existente?

A gente consegue usar uma lógica semelhante à de cima.

In [53]:
a = np.random.randint(10, size=(10, 10))
b = np.zeros((12,12))
b[1:11,1:11] += a
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 3., 6., 6., 5., 3., 8., 7., 1., 0., 8., 0.],
       [0., 3., 0., 0., 1., 8., 0., 4., 3., 9., 3., 0.],
       [0., 8., 5., 8., 9., 8., 3., 8., 5., 1., 6., 0.],
       [0., 1., 4., 8., 4., 5., 3., 5., 3., 9., 8., 0.],
       [0., 4., 8., 3., 0., 8., 2., 8., 3., 8., 2., 0.],
       [0., 2., 5., 2., 8., 6., 5., 1., 7., 4., 6., 0.],
       [0., 6., 6., 9., 6., 1., 8., 2., 8., 5., 6., 0.],
       [0., 8., 1., 0., 7., 0., 3., 4., 5., 4., 1., 0.],
       [0., 9., 7., 0., 9., 1., 7., 5., 5., 2., 9., 0.],
       [0., 8., 0., 2., 1., 8., 8., 9., 5., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
array = np.ones((6, 6))

array = np.pad(array, 1, constant_values=0)
array

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

9) Crie uma matriz 5x5 com valores 1, 2, 3, 4 logo abaixo da diagonal

In [58]:
array = np.array([1,2,3,4,5])
matrix_array = np.tril(array, -1)
matrix_array

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 2, 0, 0, 0],
       [1, 2, 3, 0, 0],
       [1, 2, 3, 4, 0]])

In [62]:
b = np.array([1,2,3,4])
np.diag(b, -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [55]:
# Exemplo
[[0, 0, 0, 0, 0],
[1, 0, 0, 0, 0],
[0, 2, 0, 0, 0],
[0, 0, 3, 0, 0],
[0, 0, 0, 4, 0]]

[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]