# Numpy

**Relembrando**  
  
A biblioteca **NumPy** _(Numerical Python)_ proporciona uma forma eficiente de armazenagem e processamento de conjuntos de dados, e é utilizada como base para a construção da biblioteca Pandas, que estudaremos a seguir.

O diferencial do Numpy é sua velocidade e eficiência, o que faz com que ela seja amplamente utilizada para computação científica e analise de dados. 

A velocidade e eficiência é possível graças à estrutura chamada **numpy array**, que é um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

In [1]:
# A gente importa o numpy sempre chamando ele de "np"
import numpy as np

In [2]:
py_array = [1,  2,  3]

np_array = np.array(py_array)

print(np_array)
print(type(np_array))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
print(type(np_array[0]))

<class 'numpy.int32'>


In [4]:
# Vamos fazer uma comparação com um vetor do numpy
py_matriz = [[1,   2,  3],
            [4,   5,  6],
            [7,   8,  9],
            [10, 11, 12]]

np_matriz = np.array(py_matriz)

print(np_matriz)
print(type(np_matriz))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


In [6]:
np_matriz[0]

array([1, 2, 3])

In [5]:
print(type(np_matriz[0]))

<class 'numpy.ndarray'>


In [7]:
print(type(np_matriz[0][0]))

<class 'numpy.int32'>


In [8]:
# 3 atributos básicos pra um ndarray
print(np_matriz.shape)   # O formato dele
print(np_matriz.ndim)    # Quantas dimensões ele tem
print(np_matriz.dtype)   # O "dtype", que é o tipo dos elementos (número, letra, ...) dele

(4, 3)
2
int32


In [9]:
x = np.array([1, 2, 3]) # Um vetor também é um ndarray
print(type(x))
print(x.dtype)

<class 'numpy.ndarray'>
int32


In [10]:
# O dtype de um array do numpy pode ser controlado na hora que a gente cria.
py_matriz = [[1,   2,  3],
            [4,   5,  6],
            [7,   8,  9],
            [10, 11, 12]]

matriz = np.array(py_matriz, dtype=np.float64)

In [11]:
print(matriz)
print(matriz.dtype)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
float64


In [18]:
# Para selecionar um elemento de uma tabela no Python e no Numpy, tem uma ligeira diferença.
print((matriz[0][0])) # Python: Pega a primeira linha. Dela, pega o primeiro elemento.
print((matriz[0,0]))  # Numpy: Pega o elemento da linha 0, coluna 0.

1.0
1.0


Slicing com matriz

In [22]:
# Slicing funciona no numpy!
print(matriz)
print('------')
print(matriz[:,1:]) # Pegando a terceira coluna
print('------')
print(matriz[1,:]) # Pegando a segunda linha
print('------')
print(matriz[1,::-1]) # Pegando a segunda linha, e invertendo seus elementos de trás pra frente.

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
------
[[ 2.  3.]
 [ 5.  6.]
 [ 8.  9.]
 [11. 12.]]
------
[4. 5. 6.]
------
[6. 5. 4.]


**Funções numpy**  
O numpy também tem diversas funções para facilitar criação de matrizes.

In [23]:
print(np.zeros((10, 3)), end='\n\n') # O "end" muda o que o Python encaixa no fim do que ele mostra pra gente.
print(np.ones((5,2)), end='\n\n') # \n é pular linha, e é o default. \n\n pula 2 linhas.
print(np.identity(4), end='\n\n')
print(np.eye(4, 3), end='\n\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]



# Manipulações de matrizes

In [24]:
matriz

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [25]:
# Transposição de matrizes
matriz.T

array([[ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  6.,  9., 12.]])

In [31]:
array_transposto = np.transpose(matriz)
array_transposto

array([[ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  6.,  9., 12.]])

In [34]:
matriz.transpose()

array([[ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  6.,  9., 12.]])

In [35]:
x = np.array([0.1, 0.4, 1.0, 0.2, 0.7, 1.2, 1.1, 1.0, 0.9])
x.shape

(9,)

In [36]:
# Redimensionamento
x.reshape(3, 3)

array([[0.1, 0.4, 1. ],
       [0.2, 0.7, 1.2],
       [1.1, 1. , 0.9]])

In [37]:
y = np.array([0.1, 0.4, 1.0, 0.2, 0.7, 1.2, 1.1, 1.0, 0.9, 2.0,
              1.5, 1.6])
y.shape

(12,)

In [41]:
# Vejam o que acontece se as dimensões não são condizentes
y.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [49]:
# E se eu quiser retornar para um vetor
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

x.reshape((-1, 9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
# Também é possível utilizar o flatten
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# Também podemos combinar arrays diferentes.
# Imagina que temos duas features, altura e peso de pessoas físicas.
x1 = np.array([[1.67, 89.],
               [1.79, 85.],
               [1.69, 65.],
               [1.54, 57.],
               [1.50, 45.]])

# Porém, nós queremos testar agora adicionar uma terceira feature, se a pessoa é homem ou mulher.
# 1 é mulher, 0 é homem
x2 = np.array([1, 0, 1, 0, 1])

# Como podemos fazer?

In [53]:
#Podemos utilizar o concatenate
np.concatenate((x1, x2.reshape(-1, 1)), axis=1) # O valor -1 no reshape significa que não sabemos quantas linhas teremos, o próprio numpy irá definir

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [63]:
np.concatenate((x1, x2.T), axis=1) 

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [69]:
np.append(x1, x2.reshape(-1, 1), axis=1) 

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [71]:
np.insert(x1, 1, x2, axis=1)

array([[ 1.67,  1.  , 89.  ],
       [ 1.79,  0.  , 85.  ],
       [ 1.69,  1.  , 65.  ],
       [ 1.54,  0.  , 57.  ],
       [ 1.5 ,  1.  , 45.  ]])

In [72]:
np.vstack([x1.T, x2])

array([[ 1.67,  1.79,  1.69,  1.54,  1.5 ],
       [89.  , 85.  , 65.  , 57.  , 45.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  1.  ]])

In [73]:
np.vstack([x1.T, x2]).T

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [76]:
np.hstack([x1, x2.reshape(-1, 1)])

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [74]:
np.column_stack([x1, x2])

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [77]:
# Agora temos a tabela de dados abaixo.
table = np.array([[1.67, 89., 1],
                  [1.79, 85., 0],
                  [1.69, 65., 1],
                  [1.54, 57., 0],
                  [1.50, 45., 1]])

# Mas tinhamos esquecido de outras 3 pessoas!
new_table = np.array([[1.78, 91, 0],
                      [1.72, 67, 1],
                      [1.77, 76, 1]])

In [79]:
# Como podemos juntar as tabelas?
np.vstack([table, new_table])

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ],
       [ 1.78, 91.  ,  0.  ],
       [ 1.72, 67.  ,  1.  ],
       [ 1.77, 76.  ,  1.  ]])

In [85]:
np.append(table, new_table, axis=0)

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ],
       [ 1.78, 91.  ,  0.  ],
       [ 1.72, 67.  ,  1.  ],
       [ 1.77, 76.  ,  1.  ]])

In [84]:
np.append(table, new_table).reshape(-1, 3)

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ],
       [ 1.78, 91.  ,  0.  ],
       [ 1.72, 67.  ,  1.  ],
       [ 1.77, 76.  ,  1.  ]])

# Operações Básicas

In [88]:
vec1 = np.arange(0, 10, 1)
print(vec1)
print(vec1 * 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [89]:
matriz

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [90]:
#Podemos multiplicar por um escalar
matriz_dobro = 2 * matriz
matriz_dobro

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.],
       [20., 22., 24.]])

In [91]:
# Podemos somar duas matrizes
print(matriz + matriz_dobro)

[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]


In [92]:
# Multiplicação elemento por elemento
print(matriz * matriz_dobro)

[[  2.   8.  18.]
 [ 32.  50.  72.]
 [ 98. 128. 162.]
 [200. 242. 288.]]


In [95]:
print(matriz.shape)
print(matriz_dobro.shape)

(4, 3)
(4, 3)


In [98]:
# Produto matricial
print(matriz @ matriz_dobro.T)

print('----------------------------')
# Outra forma de escrever a mesma coisa
print(matriz.dot(matriz_dobro.T))

[[ 28.  64. 100. 136.]
 [ 64. 154. 244. 334.]
 [100. 244. 388. 532.]
 [136. 334. 532. 730.]]
----------------------------
[[ 28.  64. 100. 136.]
 [ 64. 154. 244. 334.]
 [100. 244. 388. 532.]
 [136. 334. 532. 730.]]


**Bora praticar!**  
  
Transforme o csv **dados_artificiais**, que está na pasta **dados**, para um numpy array (matriz)

In [107]:
lista_artificial = [[1.78881069287776, 65.6481019432242, 0],
        [1.5667844336950, 76.6427679834926, 0],
        [2.0921930548074, 55.4681853258539, 1],
        [1.7824709172724, 67.28199736248, 1],
        [1.7357669765411, 69.2890076331505, 0],
        [1.6869746476945, 56.8400511361321, 0],
        [1.7971046329794, 65.2089732846482, 1],
        [1.1873490549389, 48.1647639458379, 0],
        [1.5958914364289, 45.4106481398706, 1],
        [1.3962817760658, 67.9301133367375, 0],
        [1.6061481645731, 67.7196040973561, 0],
        [1.7075899674617, 45.6093326162225, 0],
        [1.7355131159863, 64.8454515098479, 0],
        [1.6720551819612, 39.7059515043444, 1],
        [1.7233770692063, 50.0588802056305, 1],
        [1.6845742723083, 56.5450873826135, 1],
        [1.7332589297219, 37.5121875909276, 0],
        [1.7578996592814, 57.3624223948134, 0],
        [1.9133377051681, 69.3072463864561, 1],
        [1.4560483434458, 69.3423371108747, 0]
]

matriz = np.array(lista_artificial)

Agora utilize esta matriz para calcular o IMC, utilizando a equação

```
IMC = peso / altura**2
```
e insira na nova tabela

In [108]:
calc_imc = [matriz[i][1]/(matriz[i][0]**2)  for i in range(len(matriz))]
calc_imc

[20.516033969644194,
 31.221422393286545,
 12.671862322378622,
 21.17648965106973,
 22.99754610962119,
 19.972726183561296,
 20.191130450290462,
 34.16430688742957,
 17.82998640186705,
 34.84305285178067,
 26.250839638369474,
 15.641792787462661,
 21.528993082184783,
 14.20215981997273,
 16.854679954620202,
 19.92574427273178,
 12.486637355204843,
 18.56262192376198,
 18.931951552368982,
 32.70746503885114]

In [120]:
imc_list = list()
for pessoa in matriz:
    peso = pessoa[1]
    altura = pessoa[0]
    IMC = (peso/altura**2)
    imc_list.append(IMC)

imc_array = np.array(imc_list)

new_table = np.concatenate((matriz, imc_array.reshape(-1,1)), axis=1)

new_table

array([[ 1.78881069, 65.64810194,  0.        , 20.51603397],
       [ 1.56678443, 76.64276798,  0.        , 31.22142239],
       [ 2.09219305, 55.46818533,  1.        , 12.67186232],
       [ 1.78247092, 67.28199736,  1.        , 21.17648965],
       [ 1.73576698, 69.28900763,  0.        , 22.99754611],
       [ 1.68697465, 56.84005114,  0.        , 19.97272618],
       [ 1.79710463, 65.20897328,  1.        , 20.19113045],
       [ 1.18734905, 48.16476395,  0.        , 34.16430689],
       [ 1.59589144, 45.41064814,  1.        , 17.8299864 ],
       [ 1.39628178, 67.93011334,  0.        , 34.84305285],
       [ 1.60614816, 67.7196041 ,  0.        , 26.25083964],
       [ 1.70758997, 45.60933262,  0.        , 15.64179279],
       [ 1.73551312, 64.84545151,  0.        , 21.52899308],
       [ 1.67205518, 39.7059515 ,  1.        , 14.20215982],
       [ 1.72337707, 50.05888021,  1.        , 16.85467995],
       [ 1.68457427, 56.54508738,  1.        , 19.92574427],
       [ 1.73325893, 37.

In [117]:
imc = np.array([peso/altura**2 for altura,peso,sexo in matriz])
imc = imc.reshape(20,1)
imc

array([[20.51603397],
       [31.22142239],
       [12.67186232],
       [21.17648965],
       [22.99754611],
       [19.97272618],
       [20.19113045],
       [34.16430689],
       [17.8299864 ],
       [34.84305285],
       [26.25083964],
       [15.64179279],
       [21.52899308],
       [14.20215982],
       [16.85467995],
       [19.92574427],
       [12.48663736],
       [18.56262192],
       [18.93195155],
       [32.70746504]])

| IMC             | Categoria           |   |
|-----------------|---------------------|---|
| abaixo de 16,00 | Baixo peso Grau III |   |
| 16,00 a 16,99   | Baixo peso Grau II  |   |
| 17,00 a 18.49   | Baixo peso Grau I   |   |
| 18,50 a 24,99   | Peso ideal          |   |
| 25,00 a 29,99   | Sobrepeso           |   |
| 30,00 a 34,99   | Obesidade Grau I    |   |
| 35,00 a 39,99   | Obesidade Grau II   |   |
| 40,0 e acima    | Obesidade Grau III  |   |

Agora utilize a tabela acima para indicar a qual categoria cada valor de IMC se enquadra. Insira novamente na tabela.

In [113]:
#Caio
category_list = []
for pessoa in new_table:
    imc = pessoa[-1]
    if imc < 16:
        category_list.append('Baixo peso Grau III')
    elif imc >= 16 and imc < 16.99:
        category_list.append('Baixo peso Grau II')
    elif imc >= 17 and imc < 18.49:
        category_list.append('Baixo peso Grau I')
    elif imc >= 18.5 and imc < 24.99:
        category_list.append('Peso ideal')
    elif imc >= 25 and imc < 29.99:
        category_list.append('Sobrepeso')
    elif imc >= 30 and imc < 34.99:
        category_list.append('Obesidade GRAU I')
    elif imc >= 35 and imc < 39.99:
        category_list.append('Obesidade GRAU II')
    elif imc >= 40:
        category_list.append('Obesidade GRAU III')

category_array = np.array(category_list)
final_table = np.concatenate((new_table, category_array.reshape(-1,1)), axis=1)

final_table

array(['Peso ideal', 'Obesidade GRAU I', 'Baixo peso Grau III',
       'Peso ideal', 'Peso ideal', 'Peso ideal', 'Peso ideal',
       'Obesidade GRAU I', 'Baixo peso Grau I', 'Obesidade GRAU I',
       'Sobrepeso', 'Baixo peso Grau III', 'Peso ideal',
       'Baixo peso Grau III', 'Baixo peso Grau II', 'Peso ideal',
       'Baixo peso Grau III', 'Peso ideal', 'Peso ideal',
       'Obesidade GRAU I'], dtype='<U19')

In [115]:
# Dário
categoria = []
for imc in calc_imc:
    if imc < 16:
        categoria.append('Baixo peso Grau III')
    elif imc <= 16.99:
        categoria.append('Baixo peso Grau II')
    elif imc <= 18.49:
        categoria.append('Baixo peso Grau I')
    elif imc <= 24.99:
        categoria.append('Peso ideal')
    elif imc <= 29.99:
        categoria.append('Sobrepeso')
    elif imc <= 34.99:
        categoria.append('Obesidade Grau I')
    elif imc <= 39.99:
        categoria.append('Obesidade Grau II')
    else:
        categoria.append('Obesidade Grau III')
        
categoria = np.array(categoria).reshape((len(categoria)), 1)

matriz_final = np.append(matriz, categoria, axis=1)
matriz_final

array([['1.78881069287776', '65.6481019432242', '0.0', 'Peso ideal'],
       ['1.566784433695', '76.6427679834926', '0.0', 'Obesidade Grau I'],
       ['2.0921930548074', '55.4681853258539', '1.0',
        'Baixo peso Grau III'],
       ['1.7824709172724', '67.28199736248', '1.0', 'Peso ideal'],
       ['1.7357669765411', '69.2890076331505', '0.0', 'Peso ideal'],
       ['1.6869746476945', '56.8400511361321', '0.0', 'Peso ideal'],
       ['1.7971046329794', '65.2089732846482', '1.0', 'Peso ideal'],
       ['1.1873490549389', '48.1647639458379', '0.0', 'Obesidade Grau I'],
       ['1.5958914364289', '45.4106481398706', '1.0',
        'Baixo peso Grau I'],
       ['1.3962817760658', '67.9301133367375', '0.0', 'Obesidade Grau I'],
       ['1.6061481645731', '67.7196040973561', '0.0', 'Sobrepeso'],
       ['1.7075899674617', '45.6093326162225', '0.0',
        'Baixo peso Grau III'],
       ['1.7355131159863', '64.8454515098479', '0.0', 'Peso ideal'],
       ['1.6720551819612', '39.70595150

In [121]:
# Bruno
def func_imc_class(weight):
    if weight < 16: return 'Baixo peso Grau III'
    elif weight < 17: return 'Baixo peso Grau II'
    elif weight < 18.5: return 'Baixo peso Grau I'
    elif weight < 25: return 'Peso ideal'
    elif weight < 30: return 'Sobrepeso'
    elif weight < 35: return 'Obesidade Grau I'
    elif weight < 40: return 'Obesidade Grau II'
    else: return 'Obesidade Grau III'
    
imc_class = []
for wght in imc:
    imc_class.append(func_imc_class(wght))
imc_class = np.array(imc_class)
table = np.hstack([new_table,imc_class.reshape(-1,1)])
table

array([['1.78881069287776', '65.6481019432242', '0.0',
        '20.516033969644194', 'Peso ideal'],
       ['1.566784433695', '76.6427679834926', '0.0',
        '31.221422393286545', 'Obesidade Grau I'],
       ['2.0921930548074', '55.4681853258539', '1.0',
        '12.671862322378622', 'Baixo peso Grau III'],
       ['1.7824709172724', '67.28199736248', '1.0', '21.17648965106973',
        'Peso ideal'],
       ['1.7357669765411', '69.2890076331505', '0.0',
        '22.99754610962119', 'Peso ideal'],
       ['1.6869746476945', '56.8400511361321', '0.0',
        '19.972726183561296', 'Peso ideal'],
       ['1.7971046329794', '65.2089732846482', '1.0',
        '20.191130450290462', 'Peso ideal'],
       ['1.1873490549389', '48.1647639458379', '0.0',
        '34.16430688742957', 'Obesidade Grau I'],
       ['1.5958914364289', '45.4106481398706', '1.0',
        '17.82998640186705', 'Baixo peso Grau I'],
       ['1.3962817760658', '67.9301133367375', '0.0',
        '34.84305285178067', 'Obe

### Tipos de dados

Primeiro vamos falar do infinito (e além).

Quando fazemos operações de ponto flutuante no computador, existe um padrão técnico (definido pela IEEE, o Instituto de Engenheiros Eletro-eletrônicos) que define algumas coisas que uma biblioteca tem que ter.

Especificamente, aqui vamos falar de duas coisas:
- Not a Number (NAN)
- Infinito

In [122]:
# Not a Number é o resultado de operações inválidas.
# Embora ele exista no Python, operações inválidas tendem a levantar um erro.
0/0

ZeroDivisionError: division by zero

In [123]:
# Para usá-lo no python, temos que converter string para float.
float('NaN')

nan

In [124]:
# No numpy, temos o objeto nan.
print(np.nan)
print(type(np.nan))

nan
<class 'float'>


In [125]:
# Já no numpy, operações inválidas retornam NaN mesmo.
x1 = np.array([1, 0, 1, 0])
x2 = np.array([2, 1, 2, 0])

print(x1 / x2)

[0.5 0.  0.5 nan]


C:\Users\BrunoIssamo\AppData\Local\Temp\ipykernel_15904\1780719695.py:5: RuntimeWarning: invalid value encountered in true_divide
  print(x1 / x2)


In [126]:
# "Infinito", no padrão, pode ser pensado como um número que é maior que qualquer outro número.
# No caso de "-infinito", temos um número que é menor que qualquer outro número.
1/0

ZeroDivisionError: division by zero

In [127]:
print(float('inf'))
print(float('inf') > 293818943824723984.928)
print(-float('inf') < -293818943824723984.928)

inf
True
True


In [128]:
# No Numpy, não seria diferente.
print(np.inf)
print(np.inf > 293818943824723984.928)
print(-np.inf < -293818943824723984.928)
print(type(np.inf))

inf
True
True
<class 'float'>


In [129]:
# No numpy, algumas operações podem gerar infinitos.
x1 = np.array([1, 0, 1, 0])
x2 = np.array([2, 1, 2, 0])

print(x2 / x1)

[ 2. inf  2. nan]


C:\Users\BrunoIssamo\AppData\Local\Temp\ipykernel_15904\1085014809.py:5: RuntimeWarning: divide by zero encountered in true_divide
  print(x2 / x1)
C:\Users\BrunoIssamo\AppData\Local\Temp\ipykernel_15904\1085014809.py:5: RuntimeWarning: invalid value encountered in true_divide
  print(x2 / x1)


Notou que tanto infinito quanto NaN são do tipo "float"? Não são float64, nem float32, nem anda assim.

Isso é devido à hierarquia de dtypes do numpy.

![hierarchy](https://numpy.org/doc/stable/_images/dtype-hierarchy.png)